services:
  atr-backend:
    image: syafa/atr-backend:latest
    container_name: atr-backend
    restart: always
    environment:
      LIMITER_MAX: ${LIMITER_MAX}
      LIMITER_EXPIRATION_MINUTES: ${LIMITER_EXPIRATION_MINUTES}
      BODY_LIMIT_MB: ${BODY_LIMIT_MB}
      ACCOUNT_REGISTRATION_CODE_DIGIT_COUNT: ${ACCOUNT_REGISTRATION_CODE_DIGIT_COUNT}
      PASSWORD_CHANGE_CODE_DIGIT_COUNT: ${PASSWORD_CHANGE_CODE_DIGIT_COUNT}
      PASSWORD_CHANGE_EXPIRY_MINUTES: ${PASSWORD_CHANGE_EXPIRY_MINUTES}
      PASSWORD_CHANGE_CODE_RETRY_SECONDS: ${PASSWORD_CHANGE_CODE_RETRY_SECONDS}
      APP_PORT: ${APP_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_ACCOUNT_ID: ${S3_ACCOUNT_ID}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_ACCESS_KEY_SECRET: ${S3_ACCESS_KEY_SECRET}
      S3_BUCKET_URL_PREFIX: ${S3_BUCKET_URL_PREFIX}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRED_DAYS: ${JWT_EXPIRED_DAYS}
      EMAIL_FROM: ${EMAIL_FROM}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      MAILTRAP_URL: ${MAILTRAP_URL}
      MAILTRAP_TOKEN_ACCOUNT_REGISTRATION: ${MAILTRAP_TOKEN_ACCOUNT_REGISTRATION}
      MAILTRAP_TOKEN_PASSWORD_RESET: ${MAILTRAP_TOKEN_PASSWORD_RESET}
      MAILTRAP_TEMPLATE_ACCCOUNT_REGISTRATION: ${MAILTRAP_TEMPLATE_ACCCOUNT_REGISTRATION}
      MAILTRAP_TEMPLATE_PASSWORD_RESET: ${MAILTRAP_TEMPLATE_PASSWORD_RESET}
      MAILTRAP_COMPANY_INFO_NAME: ${MAILTRAP_COMPANY_INFO_NAME}
      MAILTRAP_COMPANY_INFO_ADDRESS: ${MAILTRAP_COMPANY_INFO_ADDRESS}
      MAILTRAP_COMPANY_INFO_CITY: ${MAILTRAP_COMPANY_INFO_CITY}
      MAILTRAP_COMPANY_INFO_ZIP_CODE: ${MAILTRAP_COMPANY_INFO_ZIP_CODE}
      MAILTRAP_COMPANY_INFO_COUNTRY: ${MAILTRAP_COMPANY_INFO_COUNTRY}
    ports:
      - "8080:${APP_PORT}"
